[package]
name = "ratatui-code-editor"
version = "0.1.0"
edition = "2024"

[[example]]
name = "half"
path = "examples/half.rs"
[[example]]
name = "split"
path = "examples/split.rs"

[profile.release]
debug = true

[dependencies]
anyhow = "1.0"
crossterm = "0.29"
ratatui = "0.29"
ropey = "1.6"
rust-embed = { version = "8.7", features = ["include-exclude"] }
streaming-iterator = "0.1.9"
tree-sitter = "0.25.6"
tree-sitter-javascript = "0.23.1"
tree-sitter-rust = "0.24.0"
tree-sitter-typescript = "0.23.2"
unicode-width = "0.2.0"
arboard = { version = "3.5.0", default-features = false }
